CREATE DATABASE IF NOT EXISTS hncu CHARACTER SET utf8;

USE hncu;

CREATE TABLE student(
	id VARCHAR(32) PRIMARY KEY,
	NAME VARCHAR(30)
);

CREATE TABLE book(
	id INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(30),
	price NUMERIC(6,2),
	student_id VARCHAR(32)
);

ALTER TABLE book ADD CONSTRAINT book_student_fk FOREIGN KEY(student_id) REFERENCES student(id);